config/routes.rb
DesktopMgr::Application.routes.draw do
  post "resize/fire"
  get "apps/index"

  resources :workflows

   root :to => 'workflows#index'

end

app/models/action.rb
class Action < ActiveRecord::Base
  attr_accessible :target_key, :type_id
end

app/models/workflow.rb
class Workflow < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
require '/Applications/Zephyros.app/Contents/Resources/libs/zephyros.rb'

class AppsController < ApplicationController
  def index
    @apps = API.visible_windows.reject {|w| w.title.empty?}.map {|w| w.title}
  end
end

app/controllers/resize_controller.rb
require '/Applications/Zephyros.app/Contents/Resources/libs/zephyros.rb'

class ResizeController < ApplicationController
  def fire
  	API.all_windows.select {|w| w.title == params[:target_app] }.each do |win|
      # how about something like this
      rs = Resizer.new
      rs.send :"#{params[:position]}", win
      
    end
  end
end

app/controllers/test_action_controller.rb
require '/Applications/Zephyros.app/Contents/Resources/libs/zephyros.rb'

class TestActionController < ApplicationController
  def fire
  	API.all_windows.select {|w| w.title == params[:test_action][:application_name] }.each do |win|
      frame = win.screen.frame_without_dock_or_menu
      frame.h /= 2
      win.frame = frame
  	end
    flash.now[:success] = "Action completed successfully!"
    render 'form'
  end

  def form

  end
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  # GET /workflows
  # GET /workflows.json
  def index
    @workflows = Workflow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workflows }
    end
  end

  # GET /workflows/1
  # GET /workflows/1.json
  def show
    @workflow = Workflow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workflow }
    end
  end

  # GET /workflows/new
  # GET /workflows/new.json
  def new
    @workflow = Workflow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workflow }
    end
  end

  # GET /workflows/1/edit
  def edit
    @workflow = Workflow.find(params[:id])
  end

  # POST /workflows
  # POST /workflows.json
  def create
    @workflow = Workflow.new(params[:workflow])

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to @workflow, notice: 'Workflow was successfully created.' }
        format.json { render json: @workflow, status: :created, location: @workflow }
      else
        format.html { render action: "new" }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workflows/1
  # PUT /workflows/1.json
  def update
    @workflow = Workflow.find(params[:id])

    respond_to do |format|
      if @workflow.update_attributes(params[:workflow])
        format.html { redirect_to @workflow, notice: 'Workflow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflows/1
  # DELETE /workflows/1.json
  def destroy
    @workflow = Workflow.find(params[:id])
    @workflow.destroy

    respond_to do |format|
      format.html { redirect_to workflows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_action_helper.rb
module TestActionHelper
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Top</th>
    <th>Bottom</th>
    <th>Left</th>
    <th>Right</th>
  </tr>

<% @apps.each_with_index do |app, i| %>
  <tr>
    <td><%= i + 1 %></td>
    <td><%= app %></td>
    <td><%= link_to "Do it", resize_fire_path(target_app: app, position: 'top'), method: "post", remote: true %></td>
    <td><%= link_to "Do it", resize_fire_path(target_app: app, position: 'bottom'), method: "post", remote: true %></td>
    <td><%= link_to "Do it", resize_fire_path(target_app: app, position: 'left'), method: "post", remote: true %></td>
    <td><%= link_to "Do it", resize_fire_path(target_app: app, position: 'right'), method: "post", remote: true %></td>
  </tr>
<% end %>
</table>

app/views/layouts/_flash.html.erb
<div class="alert flash">
	<% flash.each do |name, msg| -%>
	 <%= content_tag :div, msg, class: name %>
	<% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesktopMgr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render partial: "layouts/flash", locals: { flash: flash } %>
	<%= yield %>

</body>
</html>

app/views/workflows/_form.html.erb
<%= form_for(@workflow) do |f| %>
  <% if @workflow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workflow.errors.count, "error") %> prohibited this workflow from being saved:</h2>

      <ul>
      <% @workflow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workflows/edit.html.erb
<h1>Editing workflow</h1>

<%= render 'form' %>

<%= link_to 'Show', @workflow %> |
<%= link_to 'Back', workflows_path %>

app/views/workflows/index.html.erb
<h1>Listing workflows</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workflows.each do |workflow| %>
  <tr>
    <td><%= workflow.name %></td>
    <td><%= link_to 'Show', workflow %></td>
    <td><%= link_to 'Edit', edit_workflow_path(workflow) %></td>
    <td><%= link_to 'Destroy', workflow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workflow', new_workflow_path %>

app/views/workflows/new.html.erb
<h1>New workflow</h1>

<%= render 'form' %>

<%= link_to 'Back', workflows_path %>

app/views/workflows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @workflow.name %>
</p>


<%= link_to 'Edit', edit_workflow_path(@workflow) %> |
<%= link_to 'Back', workflows_path %>